stages:
 - build
 - test
 - visualize
 - package
 - deploy
 - testqa
 - deploy-pro

#PARA GENERAR ARTEFACTOS Y REVISION DE SONAR
variables:
 JAVA_HOME : "${JAVA_HOME}"
 M2_HOME : "${M2_HOME}"
 #JAVA_HOME: "/datos/data-qa/herramientas/jdk-repo/openjdk-21.0.2"
 #M2_HOME: "/datos/data-qa/herramientas/apache-maven/apache-maven-3.9.9_sonar_243"

 #SONAR_HOME : "/opt/SDKMAN/candidates/sonar/sonar-scanner-5.0.1.3006"
 SONAR_HOME: "/datos/data-qa/herramientas/sonar-scanner/sonar-scanner-7.1.0.4889-linux-x64"
 SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
 GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
 DEPENDENCY : "/opt/SDKMAN/candidates/java/dependency-check"
 #DEPENDENCY: "/datos/data-qa/herramientas/dependency-check/dependency-check-12.1.0"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .sonar/cache
    - .cache/pip
    - venv/
    - .scannerwork/
    - .m2/


###########1 MASTER
generar:
 stage: build
 script:
   - export JAVA_HOME=$JAVA_HOME
   - export M2_HOME=$M2_HOME
   - export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH
   - mvn clean install
 when: manual
 tags:
  - jacoco

generar-sonarqube:
 stage: test
 needs: ["generar"]
 script:
  - export JAVA_HOME=$JAVA_HOME
  - export M2_HOME=$M2_HOME
  - export SONAR_HOME=$SONAR_HOME
  - export DEPENDENCY=$DEPENDENCY
  - export PATH=$DEPENDENCY/bin:$JAVA_HOME/bin:$SONAR_HOME/bin:$M2_HOME/bin:$PATH
   ### DEPENDENCY CHECK ### 
  #- mvn dependency:copy-dependencies
  #- mkdir reports
  #- dependency-check.sh -n --scan ${CI_PROJECT_DIR}/target/dependency --project "API Catalogo" -f JSON -f HTML -f XML -o reports/
  #- mvn clean verify
  #- sonar-scanner -Dproject.settings=sonar-scanner.properties -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
  - ls http://10.12.5.243:9000/dashboard?branch=master&id=sri-catalogo-api
 allow_failure: true
 when: manual
 tags:
  - jacoco

prueba-instalacion:
 stage: test
 needs: ["generar"]
 script:
  - ls
 tags:
  - jacoco

prueba-carga-api:
 stage: test
 needs: ["generar"]
 script:
  - cd /home/labqa/k6
  - k6 run test_apik6_catalog.js
 when: manual
 tags:
  - jacoco

crear-imagen:
  stage: package
  needs: ["generar-sonarqube"]
  script:
  - export JAVA_HOME=$JAVA_HOME
  - export M2_HOME=$M2_HOME
  - export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH
  - mvn package
  - podman build -f src/main/docker/Dockerfile.jvm -t sri-catalogo-api-jvm .
  when: manual
  tags:
  - jacoco

tag-imagen:
  stage: package
  needs: ["crear-imagen"]
  script:
  - podman image tag sri-catalogo-api-jvm:latest 10.2.21.21:9085/qa/sri-catalogo-api-jvm:latest
  - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - podman image push 10.2.21.21:9085/qa/sri-catalogo-api-jvm:latest
  when: manual
  tags:
  - jacoco

borrar-imagen:
  stage: deploy
  needs: ["tag-imagen"]
  script:
  - kubectl delete -f src/main/kubernetes/1-k8s-catalogo-api-deploy.yaml,src/main/kubernetes/2-k8s-catalogo-api-service.yaml,src/main/kubernetes/3-k8s-catalogo-api-ingress.yaml,src/main/kubernetes/4-k8s-catalogo-api-hpa.yaml  || true
  allow_failure: true
  when: manual
  tags:
  - jacoco

ejecutar-imagen:
  stage: deploy
  needs: ["borrar-imagen"]
  script:
  - kubectl apply -f src/main/kubernetes/1-k8s-catalogo-api-deploy.yaml,src/main/kubernetes/2-k8s-catalogo-api-service.yaml,src/main/kubernetes/3-k8s-catalogo-api-ingress.yaml,src/main/kubernetes/4-k8s-catalogo-api-hpa.yaml
  when: manual
  tags:
  - jacoco

prueba-humo-api:
  stage: testqa
  needs: ["ejecutar-imagen"]
  image: python:latest
  before_script:
  - python3.8 -m venv .venv
  - . .venv/bin/activate
  - pip3 install selenium
  - pip3 install pytest
  - pip3 install webdriver_manager
  - pip3 install --upgrade pip
  script:
  - cd /home/labqa/python
  - python3.8 test_catalogapi.py
  when: manual
  tags:
  - jacoco

ejecutar-imagen-produccion:
 stage: deploy-pro
 needs: ["prueba-humo-api"]
 script:
   - kubectl delete -f src/main/kubernetes/1-k8s-catalogo-api-deploy.yaml,src/main/kubernetes/2-k8s-catalogo-api-service.yaml,src/main/kubernetes/3-k8s-catalogo-api-ingress.yaml,src/main/kubernetes/4-k8s-catalogo-api-hpa.yaml
   - kubectl apply -f src/main/kubernetes/1-k8s-catalogo-api-deploy.yaml,src/main/kubernetes/2-k8s-catalogo-api-service.yaml,src/main/kubernetes/3-k8s-catalogo-api-ingress.yaml,src/main/kubernetes/4-k8s-catalogo-api-hpa.yaml
 when: manual
 tags:
  - run_devopsdesa