sonar.projectKey=sri-catalogo-api
sonar.projectName=API Catalogo
sonar.qualitygate.wait=true
sonar.sources=.
sonar.java.source=21
sonar.java.libraries=target/*.jar
sonar.java.binaries=.
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.exclusions=reports/**
# --- java reporting properties ---
sonar.coverage.jacoco.xmlReportPaths=target/jacoco-report
sonar.core.codeCoveragePlugin=jacoco
# --- Ubicación reportes dependency check --
sonar.dependencyCheck.reportPath=reports/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=reports/dependency-check-report.html
sonar.dependencyCheck.jsonReportPath=reports/dependency-check-report.json
sonar.exclusions=**/test/**/*.java,**/**/*.jsp,**/**/*.js,**/**/*.css,**/reports/**

