# datasource configuration
jdbc.username=ADMINISTRACION
jdbc.password=ADMINISTRACION
jdbc.url.intrasri=oracle:thin:@sri51:1521/INTRASRI
%dev.quarkus.datasource.username=${jdbc.username}
%dev.quarkus.datasource.password=${jdbc.password}
%dev.quarkus.datasource.reactive.url=${jdbc.url.intrasri}
%test.quarkus.datasource.username=${jdbc.username}
%test.quarkus.datasource.password=${jdbc.password}
%test.quarkus.datasource.reactive.url=${jdbc.url.intrasri}
quarkus.datasource.db-kind=oracle
# Configuraci�n de Hibernate ORM
#quarkus.hibernate-orm.database.generation=none
#quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.sql-load-script=no-file
##quarkus.datasource.username = DS_GEN_ADM_CATALOGO
#quarkus.datasource.password = ${ds_gen_adm_catalogo_password}
##quarkus.datasource.password = DS_GEN_ADM_CATALOGO
#quarkus.datasource.jdbc.url = ${jdbc_url_conexion_intrasri}
#quarkus.datasource.jdbc.url = jdbc:oracle:thin:@sri51:1521:INTRASRI
##quarkus.datasource.reactive.url=oracle:thin:@sri51:1521/INTRASRI
quarkus.datasource.username=${ADM_CATALOGO_USERNAME}
quarkus.datasource.password=${ADM_CATALOGO_PASSWORD}
quarkus.datasource.reactive.url=${REACTIVE_JDBC_URL_ORACLE_INTRASRI}
quarkus.datasource.reactive.max-size=20
quarkus.datasource.reactive.idle-timeout=PT10M
quarkus.datasource.reactive.max-lifetime=PT30M
quarkus.datasource.reactive.connect-timeout=PT30S
quarkus.datasource.reactive.acquisition-timeout=PT10S
#quarkus.http.cors
quarkus.http.cors=true
#quarkus.http.cors.origins=http\://localhost\:5173,http\://sripti04/,http\://0.0.0.0\:8680,http\://localhost\:8680,http\://localhost\:30002,/https\://([a-z0-9\\-_]+)\\.app\\.sri\\.gob.ec/
quarkus.http.cors.origins=http://localhost:5173,http://localhost:8081,https://localhost:8081,http://10.21.184.71:8080,http://sripti04,http://gitlab.sri.ad,http://10.12.8.40:30001,http://localhost:8780,https://([a-z0-9\\-_]+)\\.app\\.sri\\.gob.ec/,http://([a-z0-9\\-_]+)\\.sri\\.gob.ec/,http://devopslabpro.sri.gob.ec,http://devopslabpp.sri.gob.ec
quarkus.http.cors.methods=GET,PUT,POST
quarkus.http.cors.headers=Content-Type,X-Custom
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.port=8680
quarkus.http.root-path=/catalogo-anexo/v1.0

#Swagger UI
mp.openapi.scan.disable=false
quarkus.swagger-ui.always-include=true
quarkus.http.auth.permission.swagger.paths=${quarkus.http.root-path}/q/*                            
quarkus.http.auth.permission.swagger.policy=permit
#Configuracion para asegurar los servicios
quarkus.http.auth.permission.authenticated.paths=${quarkus.http.root-path}/*
#quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.http.auth.permission.authenticated.policy=permit
%dev.quarkus.oidc.auth-server-url=http://10.12.4.66/auth/realms/Intranet
%test.quarkus.oidc.auth-server-url=http://10.12.4.66/auth/realms/Intranet
#quarkus.oidc.auth-server-url=http://10.12.4.66/auth/realms/Intranet
quarkus.oidc.auth-server-url=${URL_SSO_INTRANET}/auth/realms/Intranet
#quarkus.oidc.client-id=api-catalogo
#quarkus.oidc.credentials.secret=827b483e-eacf-4d05-ac30-9f054e8d28be
#quarkus.oidc.application-type=service
#Tests
quarkus.test.continuous-testing=enabled
quarkus.http.test-port=8681
quarkus.http.test-ssl-port=8446
quarkus.http.test-timeout=10s
#configuracion jacoco
quarkus.jacoco.title=Reporte de pruebas Catalogo API
quarkus.jacoco.footer=SRI
quarkus.jacoco.includes=**/controller/*,**/service/*
#Logging
%dev.quarkus.log.level=DEBUG
%test.quarkus.log.level=DEBUG
quarkus.log.file.encoding=UTF-8
quarkus.log.level=DEBUG
quarkus.log.category."ec.gob.sri.api.catalogo".level=DEBUG
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.type.descriptor.sql.BasicBinder".level=TRACE
quarkus.log.category."io.vertx.ext.sql".level=DEBUG
#quarkus.log.category."ec.gob.sri.api.catalogo.controller".level=ERROR
quarkus.log.metrics.enabled=false
quarkus.micrometer.export.json.enabled=true
quarkus.micrometer.export.json.path=metrics/json
quarkus.micrometer.export.prometheus.path=metrics/prometheus
