#quarkus.vault.credentials-provider.intrasri.kv-path=myapps/vault-intrasri/db


# datasource configuration
quarkus.datasource.db-kind = oracle
quarkus.datasource.username = DS_GEN_ADM_CATALOGO
quarkus.datasource.password = DS_GEN_ADM_CATALOGO
quarkus.datasource.jdbc.url = jdbc:oracle:thin:@sri51:1521:INTRASRI

#quarkus.http.cors
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:8080,/https://([a-z0-9\\-_]+)\\.app\\.sri\\.gob.ec/
quarkus.http.cors.methods=GET,PUT,POST
quarkus.http.cors.headers=X-Custom
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.port=8080

quarkus.http.root-path=/catalogo/v1.0

mp.openapi.scan.disable=true

#Configuración para asegurar los servicios
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.oidc.auth-server-url=http://10.12.4.66/auth/realms/Intranet
#quarkus.oidc.client-id=api-catalogo
#quarkus.oidc.credentials.secret=827b483e-eacf-4d05-ac30-9f054e8d28be
#quarkus.oidc.application-type=service


# vault url
#quarkus.vault.url=http://localhost:8200

# path within the kv secret engine where is located the vault-quickstart secret configuration
#quarkus.vault.secret-config-kv-path=myapps/vault-quickstart/config
