# datasource configuration
quarkus.datasource.db-kind = oracle
quarkus.datasource.username = DS_GEN_ADM_CATALOGO
quarkus.datasource.password = DS_GEN_ADM_CATALOGO
quarkus.datasource.jdbc.url = jdbc:oracle:thin:@sri51:1521:INTRASRI

#quarkus.http.cors
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:8080,/https://([a-z0-9\\-_]+)\\.app\\.sri\\.gob.ec/
quarkus.http.cors.methods=GET,PUT,POST
quarkus.http.cors.headers=X-Custom
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.port=8080

#quarkus.http.root-path=/catalogo/v1.0