quarkus:
   datasource:
      db-kind: oracle
      username: DS_GEN_ADM_CATALOGO
      password: DS_GEN_ADM_CATALOGO
      jdbc:
         url: jdbc:oracle:thin:@sri51:1521:INTRASRI

   http:
      cors:
         ~: true
         origins: http://localhost:8080,/https://([a-z0-9\\-_]+)\\.app\\.sri\\.gob.ec/
         methods: GET,PUT,POST
         headers: X-Custom
         exposed-headers: Content-Disposition
         access-control-max-age: 24H
         access-control-allow-credentials: true
      port: 8080
      root-path: /catalogo/v1.0

   auth:
      permission:
         authenticated:
            paths: /*
            policy: authenticated

   oidc:
      auth-server-url: http://10.12.4.66/auth/realms/Intranet
      client-id: api-catalogo
      application-type: web-app
      credentials:
         secret: d9251f52-6051-4ad2-995c-8fb83f20ca9a

   vault:
      authentication:
         userpass:
            username: uservault
            password: passvault
      secret-config-kv-path: myapps/vault-quickstart/config